apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: wf1cexhml-python 
  janus-idp.io/tekton: wf1cexhml-python
  backstage.io/kubernetes-id: wf1cexhml-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wf1cexhml-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml